### ISSUE TITLE
React > 0.12

### ISSUE THREAD

**Issue by cadorn** [jhudson8/react-mixin-manager#4]
When using react 0.13 the mixins don't seem to register properly.

Have you tested with react 0.13? What is the plan to support react versions > 0.12?

**Comment by cadorn** [comment]
Hmm, I am getting the same `TypeError: this.triggerWith is not a function` error with react 0.12.2.

**Comment by cadorn** [comment]
I got https://github.com/jhudson8/react-backbone/tree/master/tutorials/event-driven-app/step2 working with react 0.13.3 so it must be something in my other setup.

Thanks for some amazing components!

**Comment by cadorn** [comment]
For reference I was including multiple copies of react on the same page.

**Comment by jhudson8** [comment]
glad you got it working

**Comment by cadorn** [comment]
This threw me of: http://jhudson8.github.io/fancydocs/index.html#project/jhudson8/react-events/section/React%20Component%20Events?focus=outline

`this.trigger('something-happened');` does not seem to work as `trigger` is not defined.

If I do it like the following it works: https://github.com/jhudson8/react-backbone/blob/master/tutorials/event-driven-app/step2/example.js#L49

So it appears I need to write my own helper to make the latter more concise as its a common pattern I have.

**Comment by jhudson8** [comment]
It seems that I'm lacking documentation here (I'll fix that).  Basically, I don't provide an event manager impl (on/off/once) with react-events but allow you to plug one in.  All you have to do is

```
require('react-events').mixin = YouImplClass;
```

For example, with Backbone, it would be

```
require('react-events').mixin = Backbone.Events;
```

**Comment by cadorn** [comment]
> For example, with Backbone, it would be
> require('react-events').mixin = Backbone.Events;

I am including `react-backbone` and setting `require('react-events').mixin = Backbone.Events;` does not help with:

```
var ViewLink = React.createClass({
    trigger: function() {
        return Backbone.Events.trigger.apply(this.state, arguments);
    },
    on: function() {
        return Backbone.Events.on.apply(this.state, arguments);
    },
    off: function() {
        return Backbone.Events.off.apply(this.state, arguments);
    },
    render: function() {
        var self = this;
        var triggerEvent = function() {
          self.triggerEvent(self.props.data.subComponentAlias);
        };
        return (
            <li onClick={triggerEvent}>
                {this.props.data.label}
            </li>
        );
    },
    triggerEvent: function(eventParam) {
        this.trigger('clicked', eventParam);
    }
});
```

I need to declare `trigger/on/off`.

**Comment by cadorn** [comment]
Never mind. After adding above:

```
    mixins: [
    'react-events.events'
    ],
```

It's working without `trigger/on/off` and without setting `require('react-events').mixin = Backbone.Events;` and just requiring `react-backbone`.

I must have tested this before I fixed the duplicate library inclusion.

I am new to react and grateful to have found your react-backbone lib as well. I now have the following working:

`PostgreSQL <-> Knex <-> Bookshelf <-> Endpoints <-> JSON API <-> Backbone <-> React`

**Comment by jhudson8** [comment]
Ok cool.  If you are using react-backbone, you don't need to set the mixin to be `Backbone.Events` as it is already done for you.  Also, you don't have to fully qualify the `events` mixin if you don't want to.

```
    mixins: ['events'],
```
